version: '3.8'

services:
  backend:
    build: ./back-nodejs
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user # ! cambiar
      POSTGRES_PASSWORD: password # ! cambiar
      POSTGRES_DB: mydb # ! cambiar
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
