version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Exponer el puerto 5000 al host
    expose:
      - "5000"  # Exponer el puerto dentro de la red de Docker
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    networks:
      - my-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Montar la configuración personalizada
    ports:
      - "80:80"  # Exponer el puerto 80 para que NGINX reciba las peticiones del host
    depends_on:
      - app  # Asegurarse de que la app Node.js esté levantada antes de NGINX
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
    driver: local
